Intro to Data Frames

In [30]:
import pandas as pd

In [31]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["A","B","C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [32]:
df.head(2)  #First two rows

   A  B  C
0  1  2  3
1  4  5  6

In [33]:
df.tail(2)  # Last two rows

   A  B  C
1  4  5  6
2  7  8  9

In [34]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [35]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [36]:
df.index.tolist()   # To print index as in list format

[0, 1, 2]

In [39]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,13,14]], columns=["A","B","C",], index=["x","Y","Z","L"]) # we can also specify index names

df.index.tolist()

['x', 'Y', 'Z', 'L']

In [40]:
df.info() # To et the information

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, x to L
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes

In [41]:
df.describe()  #Give more information about the data

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   7.000000   8.000000
std     3.872983   4.690416   4.690416
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   9.250000  10.250000
max    10.000000  13.000000  14.000000

In [42]:
df.nunique() # To find how many unique numbers in each cols

A    4
B    4
C    4
dtype: int64

In [43]:
df["A"].nunique() # We can also find the unique values in specific cols

4

In [44]:
df

    A   B   C
x   1   2   3
Y   4   5   6
Z   7   8   9
L  10  13  14

In [45]:
df.shape # To get the shape ( rows, cols)

(4, 3)

In [47]:
df.size # Prints total number of items

12