# Aggregating Data

In [17]:
import pandas as pd
coffee = pd.read_csv("./Warmup Data/coffee.csv")
result = pd.read_parquet("./Data/results.parquet")
ympics_data=pd.read_excel("./Data/olympics-data.xlsx", sheet_name="results")
bios=pd.read_csv("./Data/bios.csv")

In [18]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [19]:
bios['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Kirovgrad             1
Pereiaslav            1
Podgornyy             1
Kudepsta              1
Furmanov              1
Name: count, Length: 22368, dtype: int64

In [20]:
bios[bios['born_country']=='USA']['born_region'].value_counts().head(10)

born_region
California       1634
New York          990
Illinois          585
Massachusetts     530
Pennsylvania      530
New Jersey        381
Texas             368
Minnesota         365
Ohio              328
Michigan          319
Name: count, dtype: int64

In [21]:
bios[bios['born_country'] =='USA']['born_region'].value_counts().tail(25)

born_region
Utah              91
Missouri          91
North Carolina    86
Arizona           83
New Hampshire     83
Vermont           68
Mississippi       66
Alabama           64
Kentucky          62
Tennessee         62
Nebraska          60
Rhode Island      56
Montana           55
Maine             50
South Carolina    50
Alaska            45
Arkansas          42
Idaho             41
New Mexico        38
Nevada            36
South Dakota      27
West Virginia     24
Delaware          22
North Dakota      16
Wyoming           14
Name: count, dtype: int64

# Groupby Function in Pandas

In [22]:
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    265
Latte       195
Name: Units Sold, dtype: int64

In [23]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    37.857143
Latte       27.857143
Name: Units Sold, dtype: float64

In [24]:
coffee.head(3)

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [25]:
coffee['price'] = [2.5 if t == 'Espresso' else 3.0 for t in coffee['Coffee Type']]

In [26]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price': 'mean'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday             45    2.5
            Monday             25    2.5
            Saturday           45    2.5
            Sunday             45    2.5
            Thursday           40    2.5
            Tuesday            30    2.5
            Wednesday          35    2.5
Latte       Friday             35    3.0
            Monday             15    3.0
            Saturday           35    3.0
            Sunday             35    3.0
            Thursday           30    3.0
            Tuesday            20    3.0
            Wednesday          25    3.0

### Pivot Tables

In [27]:
coffee['revenue'] = coffee['Units Sold'] * coffee['price']

In [28]:
pivot = coffee.pivot(columns='Coffee Type', index='Day', values='revenue')

In [29]:
pivot.sum()

Coffee Type
Espresso    662.5
Latte       585.0
dtype: float64

In [30]:
pivot.sum(axis=1)

Day
Friday       217.5
Monday       107.5
Saturday     217.5
Sunday       217.5
Thursday     190.0
Tuesday      135.0
Wednesday    162.5
dtype: float64

### Using datetime with Groupby

In [31]:
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios['month_born'] = bios['born_date'].dt.month
bios['year_born'] = bios['born_date'].dt.year
bios.groupby([bios['year_born'],bios['month_born']])['name'].count().reset_index().sort_values('name', ascending=False)

      year_born  month_born  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]